<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link href="main.css" rel="stylesheet" type="text/css">
    <link   href="bootstrap.min.css" rel="stylesheet" type="text/css">
    <script src="bootstrap.min.js"></script>
</head>
<ul>
<li >    
<img src="img/logo.png" class="img-fluid" alt=""style="width:90px;height:60px;"><br><br>
<li>
      <a href="home.php">Home</a>
    </li>
    <li >
      <a href="client.php">Client Info</a>
    </li>
    <li>
      <a href="supplier-2.php">Supplier Info</a>
    </li>
   
	 <li>
        <a href="supplement-full.php">supplement Management</a>  
    </li>
	 <li>
        <a href="all_report_tables.php">Reports</a>  
    </li>
	<li>
        <a href="invoice-view.php">Invoices</a>  
    </li>
  
	<li>
        <a href="supp-cart-full.php">Cart-Supp</a>  
    </li>
	<li >
      <a href="index.php">Sign out </a>
    </li>
	
	
  </ul>
</div>
</html>